### PR TITLE
Ref problem

### LINKED ISSUE #1220: Cannot invoke the same component twice when using `ref` keyword
This seems to be true in all circumstances. For example, `tests/correctness/ref-cells/ref.futil` works as is (with something like `fud e ref.futil --to data --through icarus-verilog -s verilog.data ref.futil.data` from within that directory). However, adding an extra `invoke adder[out = mem]()();` after line 64 gives the following error due to duplicate signal declarations:

``` 
=====STDERR=====
/tmp/tmpv4kndu6f:1397: error: 'adder_out_addr0' has already been declared in this scope.
/tmp/tmpv4kndu6f:1392:      : It was declared here as a variable.
/tmp/tmpv4kndu6f:1398: error: 'adder_out_write_data' has already been declared in this scope.
/tmp/tmpv4kndu6f:1393:      : It was declared here as a variable.
/tmp/tmpv4kndu6f:1399: error: 'adder_out_write_en' has already been declared in this scope.
/tmp/tmpv4kndu6f:1394:      : It was declared here as a variable.
/tmp/tmpv4kndu6f:1400: error: 'adder_out_read_data' has already been declared in this scope.
/tmp/tmpv4kndu6f:1395:      : It was declared here as a variable.
/tmp/tmpv4kndu6f:1401: error: 'adder_out_done' has already been declared in this scope.
/tmp/tmpv4kndu6f:1396:      : It was declared here as a variable.
```

Verilog gives a similar error message.

This isn't merely an issue of invoking the same component by passing in the same cell(s) twice; adding another memory component `mem1 = std_mem_d1(32, 1, 1)` and calling `invoke adder[out = mem1]()()` yeilds the same error. It also doesn't seem to be an issue with memories in particular, since `tests/passes/compile-ref/ref-invoke.futil` produces the same type of error, but passes registers by reference. Removing the second `invoke` statement from this file causes it to run without error.

### PR DESCRIPTION
**Pull request by paili0628**
Fixes #1220

### CODE REVIEW

**Comment by sampsyo** [comment]
Awesome; looks good from here, modulo formatting stuff!!

File: calyx/src/passes/compile_ref.rs [hunk 1]
```diff
@@ -95,17 +99,23 @@ impl Visitor for CompileRef {
...
-                        width: port.borrow().width,
-                        direction: port.borrow().direction.reverse(),
-                        parent: ir::PortParent::Cell(WRC::from(&s.comp)),
-                        attributes: Attributes::default(),
-                    }));
-                    s.comp.borrow_mut().ports.push(p);
+
+                    // We only have to add ports to cells who have not been 
+                    // "previously" invoked
+                    if !self.visited_invokes.contains(&comp_name) {
```
Comment (rachitnigam) [inline calyx/src/passes/compile_ref.rs:105]: I'm not sure if this is the "morally correct" solution–while it works I think we should move the logic for adding ports to cells in the `start` function of the visitor and make the `invoke` function only be responsible for adding the assignments implied by the `ref` cell. Does that make sense?

**Comment by rachitnigam** [comment]
Some digging into the example. When running:
```
fud e examples/sync/sync-if.futil -s verilog.cycle_limit 500 -s futil.flags ' -p no-opt' --through icarus-verilog -s verilog.data examples/sync/sync-if.futil.data --to vcd -v > out.vcd
```

The example fails with an OOB. It seems that the first address sent to the memory is 1 which is incorrect. 

Screenshot 2022-11-12 at 5 26 11 PM

The sync code seems correct to me: the first synchronization happens before any of the memory are access which means the index should be zero. @paili0628 any thoughts?

**Comment by rachitnigam** [comment]
Also, running the design with `--to dat` indicates that it runs for 495 cycles (500 - 5 cycles for reset) which means it is never terminating:
```
% fud e examples/sync/sync-if.futil -s verilog.cycle_limit 500 -s futil.flags ' -p no-opt' --through icarus-verilog -s verilog.data examples/sync/sync-if.futil.data --to dat
{
  "cycles": 495,
```

File: calyx/src/passes/compile_ref.rs (hunk 1 above)
Comment (paili0628) [reply calyx/src/passes/compile_ref.rs:105]: But if so how can we locate the cells that have ref cells within them?

**Comment by rachitnigam** [comment]
(Oops comments about the bug are for #1251)

File: calyx/src/passes/compile_ref.rs (hunk 1 above)
Comment (rachitnigam) [reply calyx/src/passes/compile_ref.rs:105]: Presumably port_names contains the names of components that have their signatures updated. All we have to do is check if the cell parent is a component in that hashmap

File: tests/correctness/ref-cells/invoke.expect [hunk 2]
```diff
@@ -0,0 +1,5 @@
+{
+  "mem": [
+    0
```
Comment (rachitnigam) [inline tests/correctness/ref-cells/invoke.expect:3]: This looks wrong. Shouldn’t it be 2?

File: calyx/src/passes/compile_ref.rs [hunk 3]
```diff
@@ -14,7 +14,8 @@ use std::rc::Rc;
 /// 3. Remove all the ref cell mappings from the invoke statement
 /// 4. Inline all the mappings of ports to the invoke signature
 pub struct CompileRef {
-    port_names: HashMap<ir::Id, HashMap<ir::Id, HashMap<ir::Id, ir::Id>>>,
+    port_names:
+        HashMap<ir::Id, HashMap<ir::Id, HashMap<ir::Id, RRC<ir::Port>>>>,
```
Comment (rachitnigam) [inline calyx/src/passes/compile_ref.rs:18]: I'm not a huge fan of a `HashMap<HashMap<HashMap<...>>>`. Can we convince ourselves that this is needed here? If it is, then we need to update the documentation and make sure we know what each level of `HashMap` tracks

File: calyx/src/passes/compile_ref.rs [hunk 4]
```diff
@@ -64,6 +65,27 @@ impl Visitor for CompileRef {
             true,
             &mut self.port_names,
         );
+
+        for cell in comp.cells.iter() {
+            let mut new_ports: Vec<RRC<ir::Port>> = Vec::new();
+            if let Some(name) = cell.borrow().type_name() {
+                if self.port_names.contains_key(name) {
+                    for (_, submap) in self.port_names[name].iter() {
```
Comment (rachitnigam) [inline calyx/src/passes/compile_ref.rs:73]: If we do end up deciding that the triply nested Hashmap is needed, let's make this level into a structure and make these two `for` loops into a function that generates all the needed ports from the original data given an `ir::Cell`

File: calyx/src/passes/compile_ref.rs [hunk 5]
```diff
@@ -13,8 +13,34 @@ use std::rc::Rc;
 /// 2. Inline all the ports of the ref cells to the component signature
 /// 3. Remove all the ref cell mappings from the invoke statement
 /// 4. Inline all the mappings of ports to the invoke signature
+
+/// Map for storing added ports for each ref cell
+/// level of Hashmap represents:
+/// HashMap<-component name-, Hashmap<-cell name-, HashMap<-port name-, port>>>;
+type RefPortMap =
+    HashMap<ir::Id, HashMap<ir::Id, HashMap<ir::Id, RRC<ir::Port>>>>;
```
Comment (rachitnigam) [inline calyx/src/passes/compile_ref.rs:21]: Try using `port.canonical` to get `(cell_name, port_name)` tuple which can be used to index into the hashmap

File: calyx/src/passes/compile_ref.rs [hunk 6]
```diff
@@ -13,8 +13,34 @@ use std::rc::Rc;
...
+
+trait GetPorts {
+    fn get_ports(&self, comp_name: &ir::Id) -> Option<Vec<RRC<ir::Port>>>;
+}
+
+impl GetPorts for RefPortMap {
+    fn get_ports(&self, comp_name: &ir::Id) -> Option<Vec<RRC<ir::Port>>> {
```
Comment (rachitnigam) [inline calyx/src/passes/compile_ref.rs:28]: If you need to define methods on it, turn the `type` into a `struct` with exactly one element. Rust is clever enough to get rid of simple structs like that. Also, please document the method

File: calyx/src/passes/compile_ref.rs (hunk 5 above)
Comment (rachitnigam) [inline calyx/src/passes/compile_ref.rs:21]: Use `port.canonical` here to denest the HashMap by one level

**Review by rachitnigam — CHANGES_REQUESTED** [review]
Looks good apart from using `port.canonical` to index into the hashmap. Once fixed, feel free to merge

File: calyx/src/passes/compile_ref.rs (hunk 5 above)
Comment (paili0628) [reply calyx/src/passes/compile_ref.rs:21]: Seems like to use Canonical as a key of a hash map we would have to implement Compare, or Equals?

Comment (rachitnigam) [reply calyx/src/passes/compile_ref.rs:21]: I think that should be fine to `derive` on `ir::Canonical`

**Comment by paili0628** [comment]
Alright the debug refcell feature of rust failed to provide useful information. I have pushed the broken code. @rachitnigam can you take a look?

**Comment by rachitnigam** [comment]
@paili0628 I fixed the problem by running the VSCode debugger and tracking where the borrow error was coming. The problem was the `cell.borrow_mut()` which was being kept alive because the `ports_inline` iterator was not collected. I fixed the problem but there seems to be some other bug in the code.
