### PR TITLE
Patch for the static timing bug

### LINKED ISSUE #608: static-timing pass generates conflicting assignments for while loops
_Originally posted by @sampsyo in https://github.com/cucapra/calyx/issues/574#issuecomment-884985023_

Starting with this reduced Calyx program:

```
import "primitives/core.futil";

component main() -> () {
  cells {
    zero = std_const(1, 0);
  }

  wires {
    group cond_while {
      cond_while[done] = 1'b1;
    }
  }

  control {
    while zero.out with cond_while {
      seq {}
    }
  }
}
```

And running it through standard lowering and the interpreter reveals a conflicting assignment:

```
$ fud e --to interpreter-out -s futil.flags '-p all' reduced_iter_mult.futil
✖ interpreter → interpreter-out: interpret
`./target/debug/interp  -l /Users/asampson/Documents/cu/research/futil  /var/folders/dd/z1mcgf915pd1hc83xp51d1rw0000gn/T/tmpg9dlsce_' failed:
=====STDERR=====
thread 'main' panicked at '[interpret_group]: multiple assignments to one port: fsm1.in', interp/src/interpreter/interpret_group.rs:223:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The underlying problem is probably the `static-timing` pass. The problem is somewhat easier to see if we just run the first couple of compiler phases. Taking my reduced test case above and _just_ doing pre-optimization and compilation, like so:

```
$ fud e --to futil-lowered -s futil.flags '-p pre-opt -p compile' reduced_iter_mult.futil
```

Has a `wires` section that looks roughly like this (in heavily redacted form):

```
group static_while {
  ...
  fsm.in = fsm.out != 2'd2 ? incr.out;
  ...
  fsm.in = fsm.out == 2'd2 ? 2'd0;
  ...
}
fsm.in = fsm.out == 2'd1 & !cond_stored.out ? 2'd0;
```

In my reading, here's what the static control compilation pass has generated:

* *Inside* the `static_while` group, there is the "normal" loop control. When we're at the end of the loop (state 2), go back to state 0. When we're in any other state, increment the state number using `incr`.
* *Outside* the group, as a continuous assignment, check for the loop exit condition in state 1.

I don't quite understand why one of the above is part of the group and the other is a continuous assignment, but that's probably not too important here. What *is* important is that it's easy to see why these assignments conflict! In state 1, the stuff inside `static_while` will try to increment the counter (setting `fsm.in = 2`) while, at the same time, the continuous assignment that's outside there will be attempting to exit the loop (setting `fsm.in = 0`).

The conclusion from #574 is that this does seem to be a bug in `static-timing`.

### PR DESCRIPTION
**Pull request by EclecticGriffin**
Closes #608.

This just adds another clause to the guard for the `fsm.in` increment case to keep it from overlapping with the fsm generated externally.

Also a tiny fix for an error in the WellFormed pass.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Looks like some expect tests are failing.

File: calyx/src/passes/static_timing.rs [hunk 1]
```diff
@@ -124,7 +126,7 @@ impl Visitor for StaticTiming {
                     incr["left"] = ? fsm["out"];
                     incr["right"] = ? fsm_one["out"];
                     fsm["in"] = fsm_incr ? incr["out"];
-                    fsm["write_en"] = fsm_incr ? signal_on["out"];
+                    fsm["write_en"] = body_not_done ? signal_on["out"];
```
Comment (rachitnigam) [inline calyx/src/passes/static_timing.rs:129]: Why is this change needed?

**Comment by EclecticGriffin** [comment]
I was waiting to fix the expects until people had a chance to look over the changes

File: calyx/src/passes/static_timing.rs (hunk 1 above)
Comment (EclecticGriffin) [reply calyx/src/passes/static_timing.rs:129]: I'm not entirely convinced that this couldn't also be the `fsm_incr` but this involved changing the fewest lines of the output code, but maybe for symmetry it should be the same since other writes seem to set the `write_en` on their own

Comment (rachitnigam) [reply calyx/src/passes/static_timing.rs:129]: This should remain fsm incr.

**Comment by rachitnigam** [comment]
Also worth adding a minimised version of the buggy program as a regression test.

File: calyx/src/passes/static_timing.rs (hunk 1 above)
Comment (EclecticGriffin) [reply calyx/src/passes/static_timing.rs:129]: Makes sense, I'll make the change

**Comment by EclecticGriffin** [comment]
Made the requested changes!

**Comment by rachitnigam** [comment]
Cool, if the tests pass then merge. Keep an eye out on master for the integration tests failing.
