### PR TITLE
Find fix

### LINKED ISSUE #514: Replace `groups` and `cells` Vecs in Component with LinkedHashMaps
Replacing these will allow the `find_cell` and `find_group` methods to operate in constant time rather than linear time, but will preserve iteration order. The change is not likely to be complicated but will require a bunch of places to adjust to the new signature. It may be helpful to create a wrapper method on the component to allow mut/imut iteration over these fields, rather than exposing them directly, though if Ids are changed for some reason there is the danger that the key will become out of sync with the value. This perhaps deserves a little consideration, though it would be relatively straightforward, albeit in linear time, to update the keys to match the values. 

See following thread for initial info:

Can you talk a bit more about what this is amortizing exactly? Is it because the `find_cell` and `find_group` methods are linear? The right way to fix that is just to make them use a `LinearHashMap` and have constant access in those methods directly.

_Originally posted by @rachitnigam in https://github.com/cucapra/calyx/pull/511#discussion_r634451397_

### PR DESCRIPTION
**Pull request by EclecticGriffin**
Closes #514. 

This was a painful process for what is ultimately a largely trivial change. Most of the changes aren't that interesting, as I had to correct every direct access to groups, cells, and the names thereof. However, I did have to add a little code here and there to address issues which came up due to subtle changes in mutability when directly accessing component fields. 

Also for annoying reasons, I had to make a few things closures which were previously iterators.

Anyway, making this a draft PR for the moment b/c I want to get your takes on this.

### CODE REVIEW

**Comment by EclecticGriffin** [comment]
Oh good, its throwing the same errors in the interpreter. One sec

File: calyx/src/ir/component.rs [hunk 1]
```diff
@@ -102,4 +97,56 @@ impl Component {
...
+        self.groups.insert(name, group);
+    }
+
+    /// Adds the given cell to the component.
+    pub fn add_cell(&mut self, cell: RRC<Cell>) {
+        let name = cell.borrow().name().clone();
+        self.cells.insert(name, cell);
+    }
+    /// Iterates through the given vec and adds all the cells to the component.
+    pub fn add_cells(&mut self, cells: Vec<RRC<Cell>>) {
```
Comment (rachitnigam) [inline calyx/src/ir/component.rs:123]: I assume this can't be a slice of `RRC<Cell>` because slices only return things by reference?

File: calyx/src/backend/verilog.rs [hunk 2]
```diff
@@ -370,22 +371,24 @@ fn memory_read_write(comp: &ir::Component) -> Vec<v::Stmt> {
...
-                .type_name()
-                .map(|proto| proto.id.contains("mem"))
-                .unwrap_or_default()
-        {
-            Some(cell.borrow().name.id.clone())
-        } else {
-            None
-        }
-    });
+    let memories = || {
```
Comment (rachitnigam) [inline calyx/src/backend/verilog.rs:374]: Why is it necessary to make this a closure?

File: calyx/src/ir/structure.rs [hunk 3]
```diff
@@ -123,7 +123,7 @@ pub enum CellType {
 #[derive(Debug)]
 pub struct Cell {
     /// Name of this cell.
-    pub name: Id,
+    pub(super) name: Id,
```
Comment (rachitnigam) [inline calyx/src/ir/structure.rs:126]: Does this need to be `pub(super)` or can we just make it private?

File: calyx/src/passes/clk_insertion.rs [hunk 4]
```diff
@@ -28,18 +28,20 @@ impl Visitor for ClkInsertion {
     ) -> VisResult {
         let builder = ir::Builder::from(comp, sigs, false);
 
-        for cell_ref in &builder.component.cells {
+        let mut continuous_assignments =
+            std::mem::take(&mut builder.component.continuous_assignments);
```
Comment (rachitnigam) [inline calyx/src/passes/clk_insertion.rs:32]: What does this line do? If we need to use this pattern generally, I'd rather have it abstracted over in some method than have to explain `mem::take` to people.

File: calyx/src/ir/component.rs (hunk 1 above)
Comment (EclecticGriffin) [reply calyx/src/ir/component.rs:123]: Yeah, since it's adding the cells it needs to have ownership over them. If we wanted the method to clone the RRCs it could take a slice. Another option would be to have it take something that implements Iterator over the owned values, rather than a reference to them. That might be a better choice since it doesn't really need to be a vector.

File: calyx/src/backend/verilog.rs (hunk 2 above)
Comment (EclecticGriffin) [reply calyx/src/backend/verilog.rs:374]: This is a bit funky. The short version is that the return type of `iter_cells` and `iter_groups` is a _thing_ that implements Iterator returning references to RRCs of the appropriate type. I figured this was a reasonable encapsulation since it wasn't necessary to expose precisely how the iterator was constructed. Unfortunately, this has the side-effect of _only_ providing functionality related to the `Iterator` trait and in this particular case, it means that the iterators are not cloneable. Since this code wanted to construct an iterator and then clone it (rather than construct it twice) it ran into an error when trying to clone it. Rather than construct the iterator multiple times explicitly, I opted for a smaller code change to make what was originally the iterator a closure that returns an iterator. I would imagine this is performance-wise the same as the code that clones it.

If this seems overly silly, a possible solution would be to create a custom Trait that requires both Iterator and Clone and return something of that type when iterating over the cells and groups rather than returning something that only promises to implement Iterator.

File: calyx/src/passes/clk_insertion.rs (hunk 4 above)
Comment (EclecticGriffin) [reply calyx/src/passes/clk_insertion.rs:32]: So the problem in this particular file was that we wanted to iterate over the cells and push changes into the continuous assignments. Originally this was fine because the iteration took an immutable reference to the cells field and then a mutable reference was taken to the continuous assignments field from the mutable reference to the component.

Since cells is no longer directly accessible this means that iterating over it now takes an immutable reference to the whole component through the `iter_cells` method, rather than just the cells field on the component. This unfortunately makes it impossible to mutably access continuous_assignments through the component since it already has an immutable access being used to iterate. It took me a while to wrap my head around why the original code worked and why the change of iterating through a method didn't.

Anyway, to solve this we just needed to separate the continuous assignments from the component for the duration of the iteration, so all this line is doing is taking the current continuous assignments out of the component (temporarily replacing them with an empty vec within the component) and putting them in a mutable local variable so we can iterate through the component method and still make changes. At the end we reassign the (changed) continuous assignments back in to the component and erase the temporary vector.

We could abstract over this, though it would just be a single line invoking `mem::take` so I'm not sure that's much of a win. Is `mem::take` considered confusing in general?

File: calyx/src/ir/component.rs [hunk 5]
```diff
@@ -78,21 +79,15 @@ impl Component {
     where
         S: Clone + AsRef<str>,
     {
-        self.groups
-            .iter()
-            .find(|&g| g.borrow().name == *name)
-            .map(|r| Rc::clone(r))
+        self.groups.get(&name.as_ref().into()).map(|r| Rc::clone(r))
```
Comment (sgpthomas) [inline calyx/src/ir/component.rs:82]: woohoo constant time lookup

File: calyx/src/ir/component.rs (hunk 1 above)
Comment (sgpthomas) [reply calyx/src/ir/component.rs:123]: is there a reason not to clone the Rc's here?

File: calyx/src/backend/verilog.rs (hunk 2 above)
Comment (sgpthomas) [reply calyx/src/backend/verilog.rs:374]: I'm in favor of creating a custom iterator rather than having those methods return `impl Iterator<..>`. And then we can make this thing cloneable and it probably gives us more flexibility in the future

File: calyx/src/passes/clk_insertion.rs (hunk 4 above)
Comment (sgpthomas) [reply calyx/src/passes/clk_insertion.rs:32]: This highlights one of the downsides of these kinds of abstractions in rust atm. When you access field names directly, Rust can figure out that you are only mutating part of a structure and thus you can still have access to the rest of it. However, when you hide things behind methods Rust can no longer figure this out because there is no way to express this info in the type of a function.

That being said, abstraction is still nice. One possible solution is to have a function with a type something like:
```
fn iter_cells_cont_assgn_mut(&mut self, f: fn(&Cell, &mut Vec<cont assgn>) -> ())
```
so that internal to the function, Rust can work with the disjoint structure information. This has the downside of not letting you use a for loop, but I think that's ok.

File: calyx/src/passes/dead_cell_removal.rs [hunk 6]
```diff
@@ -52,24 +52,23 @@ impl Visitor for DeadCellRemoval {
...
+                    .map(|c| c.borrow().name().clone()),
             )
         }
 
         // All cells used in continuous assignments.
         self.used_cells.extend(
             &mut analysis::ReadWriteSet::uses(&comp.continuous_assignments)
                 .into_iter()
-                .map(|c| c.borrow().name.clone()),
+                .map(|c| c.borrow().name().clone()),
```
Comment (sgpthomas) [inline calyx/src/passes/dead_cell_removal.rs:67]: I wonder if we can have a `GetName` trait that we implement for `RRC<Group>` and `RRC<Component>` etc. so that we don't have to write `.borrow()` everywhere. This is just a thought and maybe not part of this PR.

**Review by sgpthomas — APPROVED** [review]

File: calyx/src/passes/dead_cell_removal.rs (hunk 6 above)
Comment (EclecticGriffin) [reply calyx/src/passes/dead_cell_removal.rs:67]: I was having a similar thought while writing this, could be nice. The only downside is covering up the borrow could potentially make a runtime borrow conflict harder to diagnose.

File: calyx/src/ir/component.rs (hunk 1 above)
Comment (EclecticGriffin) [reply calyx/src/ir/component.rs:123]: The only reason not to is that the one place this functionality is needed explicitly constructs the vector to be passed in and so already does the requisite cloning. I don't think that's particularly compelling, but I was trying to make the minimum number of changes to the code behavior and tried to match the ownership behavior to the extent possible.

File: calyx/src/backend/verilog.rs (hunk 2 above)
Comment (EclecticGriffin) [reply calyx/src/backend/verilog.rs:374]: Do you mean making a specific Iterator implementation or making a "super"-trait to encompass both `Clone` and `Iterator`?

If the former, we can just change the return type to the concrete iterator being returned, rather than "something that implements Iterator". Conceptually, I don't really have a problem with it, but it does feel like it is a bit of a leaky API since things outside shouldn't have to care about what exact thing is implementing iterator

File: calyx/src/passes/clk_insertion.rs (hunk 4 above)
Comment (EclecticGriffin) [reply calyx/src/passes/clk_insertion.rs:32]: Personally I find that less intuitive than doing what I did, but I also wrote what I did so that's not saying much. Passing in a function type definitely makes sense though and would likely simplify things somewhat, so maybe that's the way to go.

Comment (EclecticGriffin) [reply calyx/src/passes/clk_insertion.rs:32]: One other option would be to wrap the map construct for the cells and groups with a custom struct which exposes the methods that we directed through the component itself and make those fields public again. Downside is that it again reveals more about the internal representation that is not necessarily in-scope for people using the component, though I don't know how much of an issue that is

File: calyx/src/backend/verilog.rs (hunk 2 above)
Comment (sgpthomas) [reply calyx/src/backend/verilog.rs:374]: Yeah I see what you mean. But this also how a lot of Rust libraries seem to work? I think? Not entirely sure why tbh

Comment (EclecticGriffin) [reply calyx/src/backend/verilog.rs:374]: Seems a bit odd to me, but I guess it's not a big deal as long as people don't end up depending on special features of a given iterator implementation which aren't necessarily guaranteed

Comment (EclecticGriffin) [reply calyx/src/backend/verilog.rs:374]: Turns out `impl Clone + Iterator<Item = &RRC<T>>` is totally allowed. I feel very silly.

File: calyx/src/ir/structure.rs (hunk 3 above)
Comment (EclecticGriffin) [reply calyx/src/ir/structure.rs:126]: Correction, should probably leave it as `pub(super)` since the builder creates cells and groups directly, unless we want to create explicit constructors for cell and group.

**Comment by EclecticGriffin** [comment]
Marking as ready for review. I created a new struct called `IdList` to wrap over the linked hashmap and made these structs publicly accessible from the component, rather than having the component try to wrap over the functionality directly.

Also included the `GetName` and `CloneName` traits as a general utility though the latter is needed to make the generic definition of IdList work.

File: calyx/src/ir/component.rs [hunk 7]
```diff
@@ -103,3 +98,84 @@ impl Component {
...
+    /// Add multiple elements to the collection from an owned vector
+    pub fn add_multiple(&mut self, items: Vec<RRC<T>>) {
+        for item in items {
+            self.add(item)
+        }
+    }
+
+    /// Add multiple elements to the collection from a slice. This will create
+    /// new clones of the given RRCs.
+    pub fn add_multiple_by_ref(&mut self, items: &[RRC<T>]) {
```
Comment (rachitnigam) [inline calyx/src/ir/component.rs:143]: Is this used anywhere?

File: calyx/src/ir/component.rs [hunk 8]
```diff
@@ -103,3 +98,84 @@ impl Component {
...
+    }
+
+    /// Add a new element to the colleciton
+    pub fn add(&mut self, item: RRC<T>) {
+        let name = item.clone_name();
+        self.0.insert(name, item);
+    }
+
+    /// Add multiple elements to the collection from an owned vector
+    pub fn add_multiple(&mut self, items: Vec<RRC<T>>) {
```
Comment (rachitnigam) [inline calyx/src/ir/component.rs:135]: Rust's iter canonically has `extend` to extend a collection with the contents of another collection: https://doc.rust-lang.org/std/iter/trait.Extend.html

Maybe we can use the same name unless there is a good reason not to?

**Comment by rachitnigam** [comment]
Two minor comments. Resolve with discretion and merge!

File: calyx/src/ir/component.rs (hunk 7 above)
Comment (EclecticGriffin) [reply calyx/src/ir/component.rs:143]: not currently, but someone had made a comment about not needing RRC ownership so I added this

File: calyx/src/ir/component.rs (hunk 8 above)
Comment (EclecticGriffin) [reply calyx/src/ir/component.rs:135]: sure, I can implement this as extend instead, that's nice
