### PR TITLE
Fixes for the Playground

### LINKED ISSUE #978: Playground deployment broken
Why? I do not know. It is 12am and I must sleep

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #978.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Need a better solution than just duplicating the execute plan stuff

File: web/rust/src/lib.rs [hunk 1]
```diff
@@ -50,6 +50,7 @@ fn compile(
 
 #[wasm_bindgen]
 pub fn run(passes: &JsValue, library: &str, namespace: &str) -> String {
+    std::panic::set_hook(Box::new(console_error_panic_hook::hook));
```
Comment (sampsyo) [inline web/rust/src/lib.rs:53]: Turning panics into `console.log`s is a neat solution!

File: calyx/src/pass_manager.rs [hunk 2]
```diff
@@ -176,6 +176,27 @@ impl PassManager {
 
         Ok(())
     }
+
+    /// Executes a given "plan" constructed with logging disabled
+    pub fn execute_plan_without_log(
```
Comment (sampsyo) [inline calyx/src/pass_manager.rs:181]: I don't know if this is a good idea, but one option would be to use [a wasm-specific logger](https://crates.io/crates/wasm-logger), sort of analogously to the wasm-specific panic hook.

**Review by sampsyo — COMMENTED** [review]
Just a quick thought within!

File: calyx/src/pass_manager.rs (hunk 2 above)
Comment (rachitnigam) [reply calyx/src/pass_manager.rs:181]: Thanks for the reference! I'm trying to see if there is a shim for the Instant::now() implementation somewhere that I can use. If not, this might be the way to go.
