### PR TITLE
Smoosher merge many implementation

### LINKED ISSUE #585: Create merging for smooshers with # of forks > 2
Currently the Smoosher DS doesn't support that and so fails at parallel execution forking.

### PR DESCRIPTION
**Pull request by ai-cu**
Addition of fork_from_tail and merge_many functionality into the smoosher. Closes #585

### CODE REVIEW

**Comment by rachitnigam** [comment]
Fix the issues reported by `cargo clippy`.

File: interp/src/interpreter/interpret_control.rs [hunk 1]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
+//     let pv = stk_env::Smoosher::merge(st1.pv_map, st2.pv_map);
+//     out.pv_map = pv;
+//     out
+// }
+
+// fn folder(env: InterpreterState, new: &InterpreterState) -> InterpreterState {
+//     let nw = new.borrow_mut();
+//     state_merger(env, new.fork())
+// }
+
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:61]: If these are no longer required, delete these comments

File: interp/src/interpreter/interpret_control.rs [hunk 2]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
 /// Interpret Par
-/// at the moment behaves like seq
+/// current progress for par, will be updated in the next PR considering new
+/// smoosher changes
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:64]: Update this comment

File: interp/src/interpreter/interpret_control.rs [hunk 3]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
-    _continuous_assignments: &[ir::Assignment],
-    mut _env: InterpreterState,
+    p: &ir::Par,
+    continuous_assignments: &[ir::Assignment],
+    mut env: InterpreterState,
+    comp: &ir::Component,
 ) -> FutilResult<InterpreterState> {
+    let mut sts: Vec<InterpreterState> = Vec::new();
+
+    //let mut new_env = env.fork();
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:73]: delete comment, if not needed

File: interp/src/interpreter/interpret_control.rs [hunk 4]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
+
+    for stmt in &p.stmts {
+        let new =
+            interpret_control(stmt, continuous_assignments, env.fork(), comp)?;
+        sts.push(new);
+    }
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:79]: You could replace with an `.iter().map(| x | { ... }).collect()` rather than building the vector manually

File: interp/src/interpreter/interpret_control.rs [hunk 5]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
+
+    //env = sts.iter().fold(env, folder);
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:81]: commented code

File: interp/src/interpreter/interpret_control.rs [hunk 6]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
+    for st in sts {
+        //env = state_merger(env, st);
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:83]: commented code

File: interp/src/interpreter/interpret_control.rs [hunk 7]
```diff
@@ -41,17 +43,50 @@ fn eval_seq(
...
+    }
+
     // for stmt in &p.stmts {
     //     env = interpret_control(stmt, comp.clone(), env)?;
     // }
```
Comment (EclecticGriffin) [inline interp/src/interpreter/interpret_control.rs:88]: commented code

File: interp/src/stk_env.rs [hunk 8]
```diff
@@ -645,6 +699,147 @@ impl<K: Eq + std::hash::Hash, V: Eq> Smoosher<K, V> {
...
+                Smoosher::shared_fork_point(&a, &sm)
+            {
+                if dp_first == 0 {
+                    dp_first = depth_a;
+                    smooshed.push(sm.smoosh(depth_b - 1));
+                } else {
+                    if dp_first != depth_a {
+                        panic!(
+                            "The common fork differs for one or more smooshers"
+                        )
```
Comment (EclecticGriffin) [inline interp/src/stk_env.rs:804]: May be worth remarking in the documentation that the shared fork point must be the _first_ shared point across all given branches (i.e., there are no pairs of branches with a common fork point which is "later" than the common fork point being used for the whole merge)

File: interp/src/stk_env.rs [hunk 9]
```diff
@@ -645,6 +699,147 @@ impl<K: Eq + std::hash::Hash, V: Eq> Smoosher<K, V> {
...
+            for (k, v) in sm.head {
+                if a_head.insert(k, v).is_some() {
+                    panic!("arguments of merge are not disjoint");
+                }
+            }
+            std::mem::drop(sm.tail);
+        }
+
+        let (a_new_head, a_new_tail) = a.tail.split();
+        if let Some(a_new_head) = a_new_head {
```
Comment (EclecticGriffin) [inline interp/src/stk_env.rs:830]: These two lines can be merged into a single pattern match

**Review by EclecticGriffin — COMMENTED** [review]
Looks good for the most part, I have a few comments here and there that deal with stylistic things, but otherwise I think it's good to go. It would also be nice to do some differential testing with the par -> seq pass that rachit has been cooking up as we would expect the end state of both with respect to memories to be identical.

File: interp/src/stk_env.rs (hunk 8 above)
Comment (EclecticGriffin) [reply interp/src/stk_env.rs:804]: Alternatively, if we do want to support a more robust merge-many then the code would need to identify which sets of branches must first be merged according to their shared history before the top level merge can occur, though this is definitely more complicated. It is not clear to me that this functionality is needed given the way par blocks are nested, but worth remembering that this is possible in the abstract and we should be clear about whether or not it is supported

File: interp/src/stk_env.rs (hunk 9 above)
Comment (ai-cu) [reply interp/src/stk_env.rs:826]: Changed in current and previous code, thank you

**Comment by rachitnigam** [comment]
LGTM code style wise. Implementation approval from @EclecticGriffin.

**Review by EclecticGriffin — APPROVED** [review]
LGTM
