### PR TITLE
Disallow @external outside main

### LINKED ISSUE #987: Disallow `@external` in subcomponents when generating verilog
The code generator will generate incorrect code if it sees `@external` in sub-components. When code generating Verilog, only the main module should have `@external`.

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #987.

### CODE REVIEW

File: calyx/src/passes/well_formed.rs [hunk 1]
```diff
@@ -120,68 +130,15 @@ where
...
-                Err(Error::malformed_control(
-                    format!("unmatching binding values for {name_out}, expected {id_out} to be {value_out}, instead got {value_in}"),
-                ))
-            }
-        },
-    )
-}
-
 fn same_type(proto_out: &CellType, proto_in: &CellType) -> CalyxResult<()> {
-    match (proto_out, proto_in) {
```
Comment (rachitnigam) [inline calyx/src/passes/well_formed.rs:150]: @paili0628 `CellType` implements `Eq` and therefore does not require manually equality comparison. Does this make sense?
